# based on https://docs.gitlab.com/ce/ci/docker/using_docker_build.html
# reference: https://docs.gitlab.com/ee/ci/yaml/README.html

image: docker:latest
services:
- docker:dind

stages:
- build
# - test
# - release
# - deploy

variables:
  REGISTRY_GITLAB:       registry.gitlab.com
  CONTAINER_BASE_NAME:   $REGISTRY_GITLAB/joaocc/zcash-base

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $REGISTRY_GITLAB

# ----------------------------------------------------------
build:latest:
  stage: build
  script:
    - docker build --tag $CONTAINER_BASE_NAME:latest   --pull --file Dockerfile .
    - docker push        $CONTAINER_BASE_NAME:latest

build:official:
  stage: build
  script:
    - docker build --tag $CONTAINER_BASE_NAME:official --pull --file Dockerfile.official .
    - docker push        $CONTAINER_BASE_NAME:official

# # ----------------------------------------------------------
# release:all:
#   stage: release
#   script:
#     - docker push $CONTAINER_BASE_NAME:latest
#     - docker push $CONTAINER_BASE_NAME:official
#   only:
#     - master
#   environment:
#     name: registry_gitlab
